%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(aa_inf_thrift).
-behaviour(thrift_service).


-include("aa_inf_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% process(This, Request)
function_info('process', params_type) ->
  {struct, [{1, {struct, {'aa_inf_types', 'aaRequest'}}}]}
;
function_info('process', reply_type) ->
  string;
function_info('process', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> no_function.

